server:
  port: 8082


dubbo:
  application:
    name: myConsumer

  registry:
    address: zookeeper://192.168.5.163
    timeout: 15000
    port: 2181
    check: false

  consumer:
#   启动时检查提供者是否存在，true报错，false忽略
    check: false
    timeout: 2000



#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
#spring:
#  profiles:
#    active: online
