server:
  port: 8085


dubbo:
  application:
    name: myProvider

#指定注册中心
  registry:
    address: zookeeper://192.168.5.163
    timeout: 15000
    port: 2182
    check: false


#指定通信规则
  protocol:
    name: dubbo
    port: 20881

#配置dubbo的暴露服务的包的扫描路径（后在启动类上配置）
#  scan:
#    base-packages: com.moon.provider.test



#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
#spring:
#  profiles:
#    active: online
